//
//  SethGodinStyleKit.h
//  SethGodin
//
//  Created by KraigSpear on 3/5/15.
//  Copyright (c) 2015 Spearware. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface SethGodinStyleKit : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* greenBackgroundTargets;

// Generated Images
+ (UIImage*)imageOfStandardButtonWithFrame: (CGRect)frame text: (NSString*)text;
+ (UIImage*)imageOfGreenBackground;

@end
